In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("Delivery_Logistics.csv")

In [62]:
df.head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [6]:
df.shape

(25000, 15)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   delivery_id          25000 non-null  float64
 1   delivery_partner     25000 non-null  object
 2   package_type         25000 non-null  object
 3   vehicle_type         25000 non-null  object
 4   delivery_mode        25000 non-null  object
 5   region               25000 non-null  object
 6   weather_condition    25000 non-null  object
 7   distance_km          25000 non-null  float64
 8   package_weight_kg    25000 non-null  float64
 9   delivery_time_hours  25000 non-null  object
 10  expected_time_hours  25000 non-null  object
 11  delayed              25000 non-null  object
 12  delivery_status      25000 non-null  object
 13  delivery_rating      25000 non-null  int64
 14  delivery_cost        25000 non-null  float64
dtypes: float64(4), int64(1), object(10)
memory usage: 2.9+ MB

In [8]:
df['delivery_id'].nunique()

24502

In [9]:
df['delivery_id'].value_counts().head()

delivery_id
24750.01    250
250.99      250
16591.00      1
16590.00      1
16589.00      1
Name: count, dtype: int64

In [10]:
df[df['delivery_id'] == 250.99].head()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
0,250.99,delhivery,automobile parts,bike,same day,west,clear,297.0,46.96,1970-01-01 00:00:00.000000008,1970-01-01 00:00:00.000000008,no,delivered,3,1632.7206
1,250.99,xpressbees,cosmetics,ev van,express,central,cold,89.6,47.39,1970-01-01 00:00:00.000000002,1970-01-01 00:00:00.000000003,no,delivered,5,640.1700
2,250.99,shadowfax,groceries,truck,two day,east,rainy,273.5,26.89,1970-01-01 00:00:00.000000010,1970-01-01 00:00:00.000000016,no,delivered,4,1448.1700
3,250.99,dhl,electronics,ev van,same day,east,cold,269.7,12.69,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000008,no,delivered,3,1486.5700
4,250.99,dhl,clothing,van,two day,north,foggy,256.7,37.02,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000016,no,delivered,4,1394.5600

In [11]:
rows = df[df['delivery_id'] == 250.99]
print(rows.index.min(), rows.index.max())

0 249

In [12]:
rows2 = df[df['delivery_id']== 24750.01]
print(rows2.index.min(),rows2.index.max())

24750 24999

In [13]:
df['delivery_time_hours'].value_counts().head()

delivery_time_hours
1970-01-01 00:00:00.000000006    3118
1970-01-01 00:00:00.000000005    3011
1970-01-01 00:00:00.000000007    2921
1970-01-01 00:00:00.000000004    2571
1970-01-01 00:00:00.000000008    2386
Name: count, dtype: int64

In [14]:
df['expected_time_hours'].value_counts().head()

expected_time_hours
1970-01-01 00:00:00.000000016    6302
1970-01-01 00:00:00.000000008    6287
1970-01-01 00:00:00.000000024    6186
1970-01-01 00:00:00.000000005    1080
1970-01-01 00:00:00.000000007    1051
Name: count, dtype: int64

In [15]:
df['delayed'].value_counts()

delayed
no     18331
yes     6669
Name: count, dtype: int64

In [16]:
df['delivery_status'].value_counts()

delivery_status
delivered    18331
delayed       5341
failed        1328
Name: count, dtype: int64

In [17]:
pd.crosstab(df['delayed'],df['delivery_status'])

delivery_status  delayed  delivered  failed
delayed
no                     0      18331       0
yes                 5341          0    1328

In [18]:
df.tail()

,delivery_id,delivery_partner,package_type,vehicle_type,delivery_mode,region,weather_condition,distance_km,package_weight_kg,delivery_time_hours,expected_time_hours,delayed,delivery_status,delivery_rating,delivery_cost
24995,24750.01,dhl,furniture,scooter,two day,east,foggy,80.7,3.65,1970-01-01 00:00:00.000000004,1970-01-01 00:00:00.000000016,no,delivered,5,414.45
24996,24750.01,ecom express,automobile parts,ev van,standard,west,clear,172.9,21.42,1970-01-01 00:00:00.000000005,1970-01-01 00:00:00.000000024,no,delivered,5,928.76
24997,24750.01,ekart,clothing,scooter,same day,east,rainy,168.4,4.85,1970-01-01 00:00:00.000000009,1970-01-01 00:00:00.000000008,yes,delayed,2,956.55
24998,24750.01,shadowfax,documents,ev van,standard,west,stormy,37.2,8.04,1970-01-01 00:00:00.000000006,1970-01-01 00:00:00.000000024,no,delivered,5,210.12
24999,24750.01,blue dart,pharmacy,ev bike,two day,central,rainy,279.3,5.06,1970-01-01 00:00:00.000000007,1970-01-01 00:00:00.000000016,no,delivered,3,1411.68

In [19]:
df['actual_hours']= df['delivery_time_hours'].str[-9:].astype(int)

In [20]:
df['expected_hours'] = df['expected_time_hours'].str[-9:].astype(int)

In [21]:
df[['actual_hours','expected_hours']].describe()

       actual_hours  expected_hours
count  25000.000000    25000.000000
mean       6.248040       13.107680
std        3.140935        7.559024
min        0.000000        2.000000
25%        4.000000        8.000000
50%        6.000000        8.000000
75%        8.000000       16.000000
max       19.000000       24.000000

In [22]:
df[df['actual_hours']==0]['delivery_status'].value_counts()

delivery_status
delivered    255
Name: count, dtype: int64

In [23]:
(df['actual_hours'] > df['expected_hours']).sum()

np.int64(5466)

In [24]:
pd.crosstab(df['actual_hours'] > df['expected_hours'], df['delivery_status'])

delivery_status  delayed  delivered  failed
row_0
False                963      18331     240
True                4378          0    1088

In [25]:
df['bad_id_flag'] = df['delivery_id'].duplicated(keep=False).astype(int)
df['bad_id_flag'].sum()

np.int64(500)

In [26]:
df['clean_id'] = df.index + 1

In [27]:
df['clean_id'].nunique()

25000

In [28]:
df['zero_time_flag'] = (df['actual_hours']==0).astype(int)
df['zero_time_flag'].sum()

np.int64(255)

In [29]:
df['delay_hours'] = df['actual_hours'] - df['expected_hours']
df[['actual_hours','expected_hours','delay_hours']].head()

   actual_hours  expected_hours  delay_hours
0             8               8            0
1             2               3           -1
2            10              16           -6
3             6               8           -2
4             9              16           -7

In [30]:
df['is_late'] = (df['delay_hours'] > 0).astype(int)
df['is_late'].sum()

np.int64(5466)

In [33]:
df['is_failed'] = (df['delivery_status'] == 'failed').astype(int)
df['is_failed'].sum()

np.int64(1328)

In [34]:
df['late_not_failed'] = ((df['is_late'] == 1) & (df['is_failed'] == 0)).astype(int)
df['late_not_failed'].sum()

np.int64(4378)

In [35]:
df.to_csv("delivery_logistics_clean.csv", index=False)

In [42]:
from google.colab import files
files.download("delivery_logistics_clean.csv")

In [36]:
import sqlite3
conn = sqlite3.connect("delivery.db")
df.to_sql("deliveries", conn, if_exists="replace", index=False)
pd.read_sql("SELECT COUNT(*) FROM deliveries", conn)

   COUNT(*)
0     25000

In [37]:
df.shape

(25000, 24)

In [38]:
df.columns.tolist()

['delivery_id',
 'delivery_partner',
 'package_type',
 'vehicle_type',
 'delivery_mode',
 'region',
 'weather_condition',
 'distance_km',
 'package_weight_kg',
 'delivery_time_hours',
 'expected_time_hours',
 'delayed',
 'delivery_status',
 'delivery_rating',
 'delivery_cost',
 'actual_hours',
 'expected_hours',
 'bad_id_flag',
 'clean_id',
 'zero_time_flag',
 'delay_hours',
 'is_late',
 'is_failed',
 'late_not_failed']

In [39]:
import pandas as pd
import sqlite3

# 1. Load the ORIGINAL file fresh (this wipes out any messed-up version of df)
df = pd.read_csv("Delivery_Logistics.csv")

# 2. Turn the fake 1970 dates into real hours (new columns)
df['actual_hours'] = df['delivery_time_hours'].str[-9:].astype(int)
df['expected_hours'] = df['expected_time_hours'].str[-9:].astype(int)

# 3. Flag the repeated IDs and make a new unique ID
df['bad_id_flag'] = df['delivery_id'].duplicated(keep=False).astype(int)
df['clean_id'] = df.index + 1

# 4. Flag the zero-hour deliveries
df['zero_time_flag'] = (df['actual_hours'] == 0).astype(int)

# 5. Calculate delay and the late / failed columns
df['delay_hours'] = df['actual_hours'] - df['expected_hours']
df['is_late'] = (df['delay_hours'] > 0).astype(int)
df['is_failed'] = (df['delivery_status'] == 'failed').astype(int)
df['late_not_failed'] = ((df['is_late'] == 1) & (df['is_failed'] == 0)).astype(int)

# 6. Check everything matches what we found before
print(df.shape)
print(df['bad_id_flag'].sum(), df['zero_time_flag'].sum(), df['is_late'].sum(), df['is_failed'].sum(), df['late_not_failed'].sum())

(25000, 24)
500 255 5466 1328 4378

In [40]:
conn = sqlite3.connect("delivery.db")
df.to_sql("deliveries", conn, if_exists="replace", index=False)
pd.read_sql("SELECT COUNT(*) FROM deliveries", conn)

   COUNT(*)
0     25000

In [41]:
pd.read_sql("""
    SELECT delivery_id,COUNT(*) AS TimesUsed
    FROM deliveries
    GROUP BY delivery_id
    HAVING COUNT(*)>1""",conn)

   delivery_id  TimesUsed
0       250.99        250
1     24750.01        250

In [42]:
pd.read_sql("""
    SELECT delivery_partner, AVG(late_not_failed) AS late_rate
    FROM deliveries
    GROUP BY delivery_partner
    ORDER BY late_rate DESC""",conn)

   delivery_partner  late_rate
0        xpressbees   0.191791
1      ecom express   0.183688
2         shadowfax   0.180556
3             ekart   0.178508
4  amazon logistics   0.173737
5               dhl   0.168808
6         blue dart   0.168692
7             fedex   0.167495
8         delhivery   0.162958

In [43]:
pd.read_sql("""
SELECT region,
       AVG(late_not_failed) AS late_rate
FROM deliveries
GROUP BY region
ORDER BY late_rate DESC
""", conn)

    region  late_rate
0  central   0.180830
1     west   0.178214
2    north   0.178016
3    south   0.173197
4     east   0.165074

In [44]:
pd.read_sql("""
SELECT weather_condition,
       AVG(late_not_failed) AS late_rate
FROM deliveries
GROUP BY weather_condition
ORDER BY late_rate DESC
""", conn)

  weather_condition  late_rate
0            stormy   0.295379
1             rainy   0.271158
2             foggy   0.198862
3             clear   0.098691
4               hot   0.095642
5              cold   0.088023

In [45]:
pd.read_sql("""
SELECT weather_condition, clean_id, delivery_partner, delay_hours
FROM (
    SELECT weather_condition, clean_id, delivery_partner, delay_hours,
           ROW_NUMBER() OVER (
               PARTITION BY weather_condition
               ORDER BY delay_hours DESC
           ) AS rn
    FROM deliveries
    WHERE is_failed = 0
)
WHERE rn = 1
""", conn)

  weather_condition  clean_id  delivery_partner  delay_hours
0             clear     10612         shadowfax            7
1              cold       591  amazon logistics            6
2             foggy      1769         delhivery            9
3               hot      4586         shadowfax            6
4             rainy      1881               dhl           10
5            stormy      5597             fedex           12